school/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from school import settings
from management.StaffViews import *
from management.StudentViews import *
from management.EditResultViewClass import EditResultViewClass

from management.HodViews import *
from django.urls import include
from management.views import HomePage, ShowLoginPage, doLogin, GetUserDetails, logout_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', HomePage),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', ShowLoginPage, name="show_login"),
    path('get_user_details', GetUserDetails),
    path('logout', logout_user, name="logout"),
    path('admin_home', admin_home, name="admin_home"),
    path('doLogin', doLogin, name="login"),
    path('add_staff_save', add_staff_save, name="add_staff_save"),
    path('add_course', add_course, name="add_course"),
    path('manage_course', manage_course, name="manage_course"),
    path('add_course_save', add_course_save, name="add_course_save"),
    path('add_student', add_student, name="add_student"),
    path('manage_student', manage_student, name="manage_student"),
    path('add_student_save', add_student_save, name="add_student_save"),
    path('add_subject_save', add_subject_save, name="add_subject_save"),
    path('add_subject', add_subject, name="add_subject"),
    path('manage_subject', manage_subject, name="manage_subject"),    
    path('add_staff', AddStaff, name="add_staff"),
    path('manage_staff', manage_staff, name="manage_staff"),
    path('edit_staff/<str:staff_id>', edit_staff, name="edit_staff"),
    path('edit_student/<str:student_id>', edit_student, name="edit_student"),
    path('edit_staff_save', edit_staff_save, name="edit_staff_save"),
    path('edit_subject/<str:subject_id>', edit_subject, name="edit_subject"),
    path('edit_course/<str:course_id>', edit_course, name="edit_course"),
    path('edit_subject_save', edit_subject_save, name="edit_subject_save"),
    path('edit_course_save', edit_course_save, name="edit_course_save"),
    path('edit_student_save', edit_student_save, name="edit_student_save"),  
    path('manage_session', manage_session, name="manage_session"),
    path('add_session_save', add_session_save, name="add_session_save"),
    path('check_email_exist', check_email_exist,name="check_email_exist"),
    path('check_username_exist', check_username_exist,name="check_username_exist"),
    path('student_feedback_message', student_feedback_message,name="student_feedback_message"),
    path('staff_feedback_message', staff_feedback_message,name="staff_feedback_message"),
    path('student_feedback_message_replied', student_feedback_message_replied,name="student_feedback_message_replied"),
    path('staff_feedback_message_replied', staff_feedback_message_replied,name="staff_feedback_message_replied"),
    path('student_leave_view', student_leave_view,name="student_leave_view"),
    path('staff_leave_view', staff_leave_view,name="staff_leave_view"),
    path('student_approve_leave/<str:leave_id>', student_approve_leave,name="student_approve_leave"),
    path('student_disapprove_leave/<str:leave_id>', student_disapprove_leave,name="student_disapprove_leave"),
    path('staff_disapprove_leave/<str:leave_id>', staff_disapprove_leave,name="staff_disapprove_leave"),
    path('staff_approve_leave/<str:leave_id>', staff_approve_leave,name="staff_approve_leave"),
    path('admin_profile', admin_profile,name="admin_profile"),
    path('admin_profile_save', admin_profile_save,name="admin_profile_save"),
    path('student_view_result', student_view_result, name="student_view_result"),
    path('edit_session_year', edit_session_year, name="edit_session_year"), 
    path('delete_session/<str:session_id>', delete_session, name="delete_session"),
    path('delete_course/<str:course_id>', delete_course, name="delete_course"), 
    #staff_urls
    path('staff_home', staff_home, name="staff_home"),
    path('staff_apply_leave', staff_apply_leave, name="staff_apply_leave"),
    path('staff_apply_leave_save', staff_apply_leave_save, name="staff_apply_leave_save"),
    path('staff_feedback', staff_feedback, name="staff_feedback"),
    path('staff_feedback_save', staff_feedback_save, name="staff_feedback_save"),
    path('staff_profile', staff_profile,name="staff_profile"),
    path('staff_profile_save', staff_profile_save,name="staff_profile_save"),
    path('staff_add_result', staff_add_result, name="staff_add_result"),
    path('get_students', get_students, name="get_students"),
    path('save_student_result', save_student_result, name="save_student_result"),
    path('edit_student_result',EditResultViewClass.as_view(), name="edit_student_result"),
    path('staff_add_assignment',staff_add_assignment, name="staff_add_assignment"),
    path('staff_assignment_save',staff_assignment_save, name="staff_assignment_save"),
    path('staff_manage_assignment',staff_manage_assignment, name="staff_manage_assignment"),
    path('delete_assignment/<str:assignment_id>', delete_assignment, name="delete_assignment"),
    #student urls
    path('student_home', student_home, name="student_home"),
    path('view_assignments', view_assignments, name="view_assignments"),
    path('student_apply_leave', student_apply_leave, name="student_apply_leave"),
    path('student_apply_leave_save', student_apply_leave_save, name="student_apply_leave_save"),
    path('student_feedback', student_feedback, name="student_feedback"),
    path('student_feedback_save', student_feedback_save, name="student_feedback_save"),
    path('student_profile', student_profile,name="student_profile"),
    path('student_profile_save', student_profile_save,name="student_profile_save"),
    path('view_result/<str:session_id>', view_result, name="view_result"),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

management/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

TERM_CHOICES = (
    ('1st term', '1st term'),
    ('2nd term', '2nd term'),
    ('3rd term', '3rd term')
)

# Create your models here.
class CustomUser(AbstractUser):
    user_type_data=((1,"HOD"),(2,"Staff"),(3,"Student"))
    user_type=models.CharField(default=1,choices=user_type_data,max_length=10)

class AdminHOD(models.Model):
    id=models.AutoField(primary_key=True)
    admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

class Staffs(models.Model):
    id=models.AutoField(primary_key=True)
    admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    address=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

    class Meta:
        verbose_name_plural = "Staffs"
    
    def __str__(self):
        return f"{self.admin.first_name} {self.admin.last_name}"

class Courses(models.Model):
    id=models.AutoField(primary_key=True)
    course_name=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

    class Meta:
        verbose_name_plural = "Courses"

    def __str__(self):
        return self.course_name

class Subjects(models.Model):
    id=models.AutoField(primary_key=True)
    subject_name=models.CharField(max_length=255)
    course_id=models.ForeignKey(Courses,on_delete=models.CASCADE,default=1)
    staff_id=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

    class Meta:
        verbose_name_plural = "Subjects"

    def __str__(self):
        return self.subject_name

class SessionYearModel(models.Model):
    id = models.AutoField(primary_key=True)
    session_start_year = models.DateField()
    session_end_year = models.DateField()
    session_term = models.CharField(max_length=50)
    session_year_session = models.CharField(max_length=50)
    objects=models.Manager()

class Students(models.Model):
    id=models.AutoField(primary_key=True)
    admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    gender=models.CharField(max_length=255)
    profile_pic=models.FileField()
    address=models.TextField()
    course_id=models.ForeignKey(Courses,on_delete=models.DO_NOTHING)
    session_year_id = models.ForeignKey(SessionYearModel, on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

    class Meta:
        verbose_name_plural = "Students"

    def __str__(self):
        return f"{self.admin.first_name} {self.admin.last_name}"

class LeaveReportStudent(models.Model):
    id=models.AutoField(primary_key=True)
    student_id=models.ForeignKey(Students,on_delete=models.CASCADE)
    leave_date=models.CharField(max_length=255)
    leave_message=models.TextField()
    leave_status=models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

class LeaveReportStaff(models.Model):
    id = models.AutoField(primary_key=True)
    staff_id = models.ForeignKey(Staffs, on_delete=models.CASCADE)
    leave_date = models.CharField(max_length=255)
    leave_message = models.TextField()
    leave_status = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class FeedBackStudent(models.Model):
    id = models.AutoField(primary_key=True)
    student_id = models.ForeignKey(Students, on_delete=models.CASCADE)
    feedback = models.TextField()
    feedback_reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class FeedBackStaffs(models.Model):
    id = models.AutoField(primary_key=True)
    staff_id = models.ForeignKey(Staffs, on_delete=models.CASCADE)
    feedback = models.TextField()
    feedback_reply=models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

class StudentResult(models.Model):
    id=models.AutoField(primary_key=True)
    student_id=models.ForeignKey(Students,on_delete=models.CASCADE)
    subject_id=models.ForeignKey(Subjects,on_delete=models.CASCADE)
    class_result =models.ForeignKey(Courses, on_delete=models.CASCADE)
    session_year_id  = models.ForeignKey(SessionYearModel, on_delete=models.CASCADE)
    subject_exam_marks=models.FloatField(default=0)
    subject_assignment_marks=models.FloatField(default=0)
    created_at=models.DateField(auto_now_add=True)
    updated_at=models.DateField(auto_now_add=True)
    objects=models.Manager()

    def __str__(self):
        return self.student_id.admin.username

class StudentAssignments(models.Model):
    id = models.AutoField(primary_key=True)
    staff_id = models.ForeignKey(Staffs, on_delete=models.CASCADE)
    assignment = models.TextField()
    subject_id = models.ForeignKey(Subjects,on_delete=models.CASCADE)
    course_id = models.ForeignKey(Courses, on_delete=models.CASCADE)
    date_added = models.DateField(auto_now_add=True)



@receiver(post_save,sender=CustomUser)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        if instance.user_type==1:
            AdminHOD.objects.create(admin=instance)
        if instance.user_type==2:
            Staffs.objects.create(admin=instance,address="")
        if instance.user_type==3:
            Students.objects.create(admin=instance,course_id=Courses.objects.get(id=1),session_year_id=SessionYearModel.objects.get(id=1),address="",profile_pic="",gender="")

@receiver(post_save,sender=CustomUser)
def save_user_profile(sender,instance,**kwargs):
    if instance.user_type==1:
        instance.adminhod.save()
    if instance.user_type==2:
        instance.staffs.save()
    if instance.user_type==3:
        instance.students.save()

management/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from management.EmailBackend import EmailBackEnd
# Create your views here.
def HomePage(request):
    return render(request, 'index.html')

def ShowLoginPage(request):
    return render(request, 'login.html')

def doLogin(request):
    if request.method!="POST":
        return HttpResponse("<h2>Method Not Allowed</h2>")
    else:
        user = EmailBackEnd.authenticate(request, username=request.POST.get("email"), password=request.POST.get("password"))
        if user!=None:
            login(request, user)
            if user.user_type=='1':
                return HttpResponseRedirect('/admin_home')
            elif user.user_type=='2':
                return HttpResponseRedirect(reverse("staff_home"))
            else:
                return HttpResponseRedirect(reverse("student_home"))
        else:
            messages.error(request, "Invalid Login Credentials")
            return HttpResponseRedirect('/')

def GetUserDetails(request):
    if request.user!=None:
        return HttpResponse("logged")
    else:
        return HttpResponse("login")

def logout_user(request):
    logout(request)
    return HttpResponseRedirect("/")

management/templates/staff_template/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Schoool System| Staff Login</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">
  {% block custom_css %}
  {% endblock custom_css %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>     
    </ul>
    <h4 style="margin-left: 10px;margin-top: 5px;"> Student Management System Staff Login</h4>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a href="{% url 'logout' %}" class="nav-link">
          Logout
        </a>
      </li>
    </ul>
    <!-- Right navbar links -->
    
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% include 'staff_template/sidebar_template.html' with user=user %}
  <div class="content-wrapper">
  <!-- Content Wrapper. Contains page content -->
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0">{% block page_title %}{% endblock page_title %}</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{% url 'admin_home' %}">Home</a></li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
    <!-- /.content-header -->

    <!-- Main content -->
    {% block main_content  %}
    {% endblock main_content %}
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  {% include 'staff_template/footer.html' %}

  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard.js' %}"></script>

{% block custom_js %}
{% endblock custom_js %}
</body>
</html>

management/templates/staff_template/edit_student_result.html
{% extends 'staff_template/base_template.html' %}
{% block page_title %}
Edit Results
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
                    <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
             <form action="{% url 'edit_student_result' %}" method="post">
                 {% csrf_token %}
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Results</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                <div class="card-body">
                    {{ form }}
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block" id="fetch_student">Update Result</button>
                </div>
            </div>
             </form>
            <!-- /.card -->



          </div>
          </div>

      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
    $(document).ready(function(){
        $("#id_session_ids").change(function(){
            fetchStudents();
        });
        $("#id_subject_id").change(function(){
            fetchStudents();
        });

        $("#id_student_ids").change(function(){
            fetch_result_student();
        })

        function fetchStudents(){
            var session_year=$("#id_session_ids").val()
            var subject=$("#id_subject_id").val()

            $.ajax({
                url:'{% url 'get_students' %}',
                type:'POST',
                data:{subject:subject,session_year:session_year},
            })
            .done(function(response){
                var json_data=JSON.parse(response);
                console.log(json_data)
                var div_data="";
                for(key in json_data)
                {
                    div_data+="<option value='"+json_data[key]['id']+"'>ID : "+json_data[key]['id']+" : "+json_data[key]['name']+"</option>";
                }

                $("#id_student_ids").html(div_data);

            })
            .fail(function(){
                alert("Error in Fetching Student")
            });
        }

        function fetch_result_student(){
            var id_student_ids=$("#id_student_ids").val()
            var subject=$("#id_subject_id").val()

            $.ajax({
                url:'{% url 'fetch_result_student' %}',
                type:'POST',
                data:{subject_id:subject,student_id:id_student_ids},
            })
            .done(function(response){
                if(response=="False"){
                    alert("Result Not Found")
                }
                else{
                    var json_data=JSON.parse(response);
                    $("#id_assignment_marks").val(json_data['assign_marks'])
                    $("#id_exam_marks").val(json_data['exam_marks'])
                }

            })
            .fail(function(){
                alert("Error in Fetching Student")
            });
        }
    })
</script>
{% endblock custom_js %}

management/templates/staff_template/footer.html
<footer class="main-footer">
    <strong>Copyright &copy; 2020-2021<a href="#">Samuel's Web Services</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1
    </div>
  </footer>

management/templates/staff_template/sidebar_template.html
{%  load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{% url 'staff_profile' %}" class="d-block">{{user.username}}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
         
          <li class="nav-item">
            {% url 'staff_home' as staff_home %}
            <a href="{{ staff_home }}" class="nav-link {% if request.path == staff_home %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Home
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>

          <li class="nav-item">
            {% url 'staff_apply_leave' as staff_apply_leave %}
            <a href="{{ staff_apply_leave }}" class="nav-link {% if request.path == staff_apply_leave %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Staff Apply Leave
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>

          <li class="nav-item">
            {% url 'staff_feedback' as staff_feedback %}
            <a href="{{ staff_feedback }}" class="nav-link {% if request.path == staff_feedback %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Staff Feedback
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>

          <li class="nav-item">
            {% url 'staff_add_result' as staff_add_result %}
            <a href="{{ staff_add_result }}" class="nav-link {% if request.path == staff_add_result %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Add Result
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>

          <!-- <li class="nav-item">
            {% url 'edit_student_result' as edit_student_result %}
            <a href="{{ edit_student_result }}" class="nav-link {% if request.path == edit_student_result %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Edit Result
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li> -->

          <li class="nav-item">
            {% url 'staff_add_assignment' as staff_add_assignment %}
            <a href="{{ staff_add_assignment }}" class="nav-link {% if request.path == staff_add_assignment %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Add Assignment
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>
          
          <li class="nav-item">
            {% url 'staff_manage_assignment' as staff_manage_assignment %}
            <a href="{{ staff_manage_assignment }}" class="nav-link {% if request.path == staff_manage_assignment %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Manage Assignments
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

management/templates/staff_template/staff_add_assignment.html
{% extends 'staff_template/base_template.html' %}
{% block page_title %}
Add Assignment
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
                    <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
             <form action="{% url 'staff_assignment_save' %}" method="post">
                 {% csrf_token %}
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Assignments</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                <div class="card-body">
                   <div class="form-group">
                    <label>Subject </label>
                    <select class="form-control" name="subject" id="subject">
                        {% for subject in subjects %}
                          <option value="{{ subject.id }}">{{ subject.subject_name }} ({{subject.course_id.course_name}})</option>
                        {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>Assignment</label>
                    <textarea rows="5" cols="40" class="form-control" name="assignment" id="assignment">
                    </textarea>
                  </div>
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block">Add Assignment</button>
                </div>
                <div id="student_data" class="card-footer">

                </div>
            </div>
             </form>
            <!-- /.card -->



          </div>
          </div>

      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}